// Auto-generated from main.html.
// DO NOT EDIT.

library x_game;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'package:web_ui/web_ui.dart';

class Game extends WebComponent {

  /** Autogenerated from the template. */

  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated.ButtonElement __e0;
  autogenerated.DivElement __e2, __e4;
  autogenerated.Template __t;

  Game.forElement(e) : super.forElement(e);

  void created_autogenerated() {
    _root = createShadowRoot();
    __t = new autogenerated.Template(_root);
    _root.innerHtml = '''
    <button id="__e-0">New game</button>
    <div id="__e-2"></div>
    <div id="__e-4"></div>
    ''';
    __e0 = _root.query('#__e-0');
    __t.listen(__e0.onClick, ($event) { newgame(); });
    __e2 = _root.query('#__e-2');
    Node __binding1 = __t.contentBind(() => (gameStartTime));
    __e2.nodes.addAll([
      new autogenerated.Text('start time: '),
      __binding1
    ]);
    __e4 = _root.query('#__e-4');
    Node __binding3 = __t.contentBind(() => (gameCount));
    __e4.nodes.addAll([
      new autogenerated.Text('game count: '),
      __binding3
    ]);

    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __e0 = __e2 = __e4 = __t = null;
  }

  void composeChildren() {
    super.composeChildren();
    if (_root is! autogenerated.ShadowRoot) _root = this;
  }

  /** Original code from the component. */

  int gameCount = 0;
  var gameStartTime = new DateTime.now();
  void newgame(e) {
    gameStartTime = new DateTime.now();
    gameCount++;
  }
}

