// Auto-generated from main.html.
// DO NOT EDIT.

library main_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

// Original code
String curTime;

main() {
  var today = new Date.now();
  curTime = '${today.hour}:${today.minute} XM';
}

// Additional generated code

var ___e0;

autogenerated.WatcherDisposer _stopWatcher___e0_1;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  // Attach model to views.
  _stopWatcher___e0_1 = autogenerated.watchAndInvoke(() => curTime, (e) {
    ___e0.innerHTML = 'Last loaded at ${curTime}.';
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<div class="container">
<h1>banro</h1>
<p>a game of growth</p>
<div class="panel">
<div class="row">
<div id="board" class="span6">
<h3>Current board</h3>
<pre>+-------------------------------------------------+
|                        -                        |
|                     /     \                     |
|                  -           -                  |
|               /     \     /     \               |
|            -         o - o         -            |
|         /     \     /     \     /     \         |
|      -         o - o  #    o - o         -      |
|   /     \     /     \     /     \     /     \   |
|          o - o  #    o - o  #    o - o          |
|   \     /     \     /     \     /     \     /   |
|      - o  #    o - o  #    o - o  #    o -      |
|   /     \     /     \     /     \     /     \   |
|          o - o  #    o - o  #    o - o          |
|   \     /     \     /     \     /     \     /   |
|      - o  #    o - o  #    o - o  #    o -      |
|   /     \     /     \     /     \     /     \   |
|          o - o  #    o - o  #    o - o          |
|   \     /     \     /     \     /     \     /   |
|      - o  #    o - o  #    o - o  #    o -      |
|   /     \     /     \     /     \     /     \   |
|          o - o  #    o - o  #    o - o          |
|   \     /     \     /     \     /     \     /   |
|      -         o - o  #    o - o         -      |
|         \     /     \     /     \     /         |
|            -         o - o         -            |
|               \     /     \     /               |
|                  -           -                  |
|                     \     /                     |
|                        -                        |
+-------------------------------------------------+
</pre>
</div>
<div id="stats" class="span5">
<h3>Stats</h3>
</div>
</div>
<div id="actions" class="row">
<div class="well span11">
<h3>Actions</h3>
</div>
</div>
</div>
<p class="pull-right" id="__e-0">Last loaded at {{curTime}}.</p>
</div>

<script type="text/javascript" src="https://dart.googlecode.com/svn/branches/bleeding_edge/dart/client/dart.js"></script>
''';

